### ISSUE TITLE
Mostrar la lista de titulos en html

### ISSUE THREAD

**Issue by IguanaBanana** [IguanaBanana/ListAnime#13]
Conectar a la base de datos e imprimir la tabla de Titulos en html.

**Comment by ivanchenoweth** [comment]
No hay mockup, de que tabla se van a leer, cuando se conluye este issue?

**Comment by IguanaBanana** [comment]
Tuvimos problemas creando la tabla pero ya se logro conectar. Sera el pull request que haremos ahora

**Comment by IguanaBanana** [comment]
https://github.com/IguanaBanana/ListAnime/issues/11 aqui esta la tabla y base de datos

**Comment by IguanaBanana** [comment]
https://github.com/IguanaBanana/ListAnime/pull/15
