### ISSUE TITLE
Cracion de base de datos

### ISSUE THREAD

**Issue by IguanaBanana** [IguanaBanana/ListAnime#3]

**Comment by IguanaBanana** [comment]
![Image](https://github.com/IguanaBanana/ListAnime/assets/113802740/68fb1fee-82ad-4b1a-ada5-9b2e547bf399)

problemas con XAMPP para la creacion de la base de datos

**Comment by ivanchenoweth** [comment]
No veo la propuestas del la ER

**Comment by ivanchenoweth** [comment]
que se va a entregar?. El diagrama y el SQL inicial de las tabals, relaciones, y datos de prueba. (Definir el alcance de esta historia)

**Comment by IguanaBanana** [comment]
![2023-06-21 (1)](https://github.com/IguanaBanana/ListAnime/assets/113802740/774c5df2-88cf-49cd-9804-f206e0a7d105)

**Comment by IguanaBanana** [comment]
![Image](https://github.com/IguanaBanana/ListAnime/assets/113802740/8c4d8cd6-d65a-4208-b8db-db087f8dbab4)

**Comment by IguanaBanana** [comment]
![Image](https://github.com/IguanaBanana/ListAnime/assets/113802740/4640e4a1-64b5-4d27-b78b-2df6ae9c86f0)

**Comment by IguanaBanana** [comment]
[DATABASE listAnime.txt](https://github.com/IguanaBanana/ListAnime/files/11826947/DATABASE.listAnime.txt)

**Comment by ivanchenoweth** [comment]
Muy bien. Como uds. no van a trabajar con laravel, no van a usar migraciones, por lo que sugiero que suban un resplado de la exportacion de cada modificacion que hagan en la base de datos.
