### ISSUE TITLE
Recopilacion de titulos de anime

### ISSUE THREAD

**Issue by DanSaurio** [IguanaBanana/ListAnime#5]
Recaudando Información Sobre Distintos Animes

**Comment by ivanchenoweth** [comment]
Que tipo de informacion? imagenes? texto? que recursos son? 
Los van a colocar aqui? 
Cual es criterio de aceptacion (cuando esta historia estara terminada)

**Comment by DanSaurio** [comment]
Imagenes y informacion en texto, se colocara aqui.

**Comment by DanSaurio** [comment]
https://docs.google.com/document/d/1V5Mnua0Hr2O6oCpzvIvr5AQNwsHQQ59B3BE05XXlPbI/edit?usp=sharing
Documento con listanimes, texto, categorias y imagenes

**Comment by ivanchenoweth** [comment]
> https://docs.google.com/document/d/1V5Mnua0Hr2O6oCpzvIvr5AQNwsHQQ59B3BE05XXlPbI/edit?usp=sharing Documento con listanimes, texto, categorias y imagenes

No tengo acceso
